version: "3"
services:
  gq-server:
    build: .
    container_name: gq-server
    environment:
      - OPT_TYPE=GOQUIET_SERVER
      - GQ_KEY=12345678
      - SS_SERVER_ADDRESS=127.0.0.1
      #- GQ_WEBSERVER_ADDRESS=104.193.88.123:443
      #- GQ_FAST_OPEN=false
      #- GQ_SERVER_HOST=0.0.0.0
      #- GQ_SERVER_PORT=443
      #- SS_SERVER_PORT=8188
    ports:
      - 443:443
    restart: always