version: "3"
services:
  ss_client:
    build: .
    container_name: ss_client
    environment:
      - OPT_TYPE=SS_CLIENT
      - SS_SERVER_ADDRESS=127.0.0.1
      - SS_PASSWORD=12345678
      #- SS_SERVER_PORT=8188
      #- SS_LOCAL_ADDRESS=0.0.0.0
      #- SS_LOCAL_PORT=8388
      #- SS_METHOD=aes-256-cfb
      #- SS_TIMEOUT=300
    ports:
      - 8388:8388
    restart: always