version: "3"
services:
  gq-client:
    build: .
    container_name: gq-client
    environment:
      - OPT_TYPE=GOQUIET_CLIENT
      - GQ_SERVER_ADDRESS=host.docker.internal
      - GQ_KEY=12345678
      #- GQ_SERVER_NAME=www.baidu.com
      #- GQ_TICKET_TIME_HINT=3600
      #- GQ_BROWSER=chrome
      #- GQ_FAST_OPEN=false
      #- GQ_LOCAL_HOST=0.0.0.0
      #- GQ_LOCAL_PORT=8288
      #- GQ_SERVER_PORT=443
    ports:
      - 8288:8288
    restart: always